#!/bin/bash

echo "Downloading dependency metadata"

sleep 2

# Download all package metadata by name

while read line; do
  if [ ! -f "downloads/metadata/$line" ]; then

    # Check if the line contains a slash (has a directory path)
    if [[ "$line" == *"/"* ]]; then
      # Extract the directory path and create it
      dir=$(dirname "$line")
      mkdir -p "downloads/metadata/$dir"
    fi

    curl -C - -o downloads/metadata/$line https://registry.npmjs.org/$line
  else
    echo "Skipping: $line (already exists)"
  fi
done < reports/unique-depends.txt

echo "Done downloading package metadata"

# Make list of tarballs to download
# Dedup tarballs
# Download tarballs
# Check tarballs
