#!/bin/bash

#set -x

TARGET=$1

if [ -z "$TARGET" ]; then
  echo "Usage: $0 <path-to-nodejs-project(s)>"
  echo "Example: $0 ~/Projects/my-node-app"
  exit 1
fi

if [ ! -d "$TARGET" ]; then
    echo "folder $TARGET not found"
    exit 1
fi


mkdir -p reports/

# 1. Check all package.json files in path for signs of compromise
# 2. Check all folders for signs of compromise

bash ./bin/detector-pkg-json-checker.bash $TARGET >> reports/infected-folders-grep.txt
bash ./bin/detector-pkg-json-jq-checker.bash $TARGET >> reports/infected-folders-jq.txt
find $TARGET -type f -name "bun_environment.js" | while read filename; do [ $(stat -c%s "$filename" 2>/dev/null) -gt 1048576 ] && echo "$filename"; done >> reports/infected-files.txt

#while read filename; do [ $(stat -f%z "$filename" 2>/dev/null || stat -c%s "$filename" 2>/dev/null) -gt 1048576 ] && echo "$filename"; done < file.txt

if [ -s "reports/infected-folders-jq.txt" ] || [ -s "reports/infected-folders-grep.txt" ] || [ -s "reports/infected-files.txt" ]; then
    echo "⚠️🚨Your systems may be infected! ⚠⚠️🚨"
    echo "Suspicious files "

    cat reports/infected-folders-grep.txt reports/infected-folders-grep.txt reports/infected-files.txt

    echo "Press Enter to continue scanning..."
    read
fi

echo "Scanning harder . . . "

#{ [ -s reports/infected-folders-grep.txt ] || [ -s reports/infected-folders-jq.txt ]; } && echo "⚠️🚨Your systems is infected ⚠⚠️🚨" && read

mkdir -p downloads/metadata
mkdir -p downloads/pkgs

rm -rf reports/state
mkdir -p reports/state

echo "Reading all dependencies . . ."
# Dump all dependencies & versions from all package.jsons
find $TARGET -type f -name "package.json" -exec ./bin/pkg-version-jq-dumper-filtered.bash "{}" \; >> reports/state/every-pkg-depend.txt
find $TARGET -type f -name "package-lock.json" -exec ./bin/pkg-lock-version-jq-dumper-filtered.bash "{}" \; >> reports/state/every-pkg-lock-depend.txt

# Dedup dependencies with versions
sort -u reports/state/every-pkg-depend.txt reports/state/every-pkg-lock-depend.txt | awk 'NF==2'  > reports/unique-depend-versions.txt

# Dedup all package names

cat reports/unique-depend-versions.txt | awk '{print $1}' | sort -u > reports/unique-depends.txt



